/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReordenRouteImport } from './routes/_app/reorden'
import { Route as AppEquiposRouteImport } from './routes/_app/equipos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatbotRouteImport } from './routes/_app/chatbot'
import { Route as AppActividadesRouteImport } from './routes/_app/actividades'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppMovementsIndexRouteImport } from './routes/_app/movements/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppCatalogoIndexRouteImport } from './routes/_app/catalogo/index'
import { Route as AppSuppliersIdRouteImport } from './routes/_app/suppliers/$id'
import { Route as AppMovementsNewRouteImport } from './routes/_app/movements/new'
import { Route as AppMovementsIdRouteImport } from './routes/_app/movements/$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients/$id'
import { Route as AppCatalogoIdRouteImport } from './routes/_app/catalogo/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReordenRoute = AppReordenRouteImport.update({
  id: '/reorden',
  path: '/reorden',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposRoute = AppEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppActividadesRoute = AppActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIndexRoute = AppMovementsIndexRouteImport.update({
  id: '/movements/',
  path: '/movements/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIndexRoute = AppCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsNewRoute = AppMovementsNewRouteImport.update({
  id: '/movements/new',
  path: '/movements/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIdRoute = AppMovementsIdRouteImport.update({
  id: '/movements/$id',
  path: '/movements/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIdRoute = AppCatalogoIdRouteImport.update({
  id: '/catalogo/$id',
  path: '/catalogo/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/actividades': typeof AppActividadesRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipos': typeof AppEquiposRoute
  '/reorden': typeof AppReordenRoute
  '/settings': typeof AppSettingsRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/movements/new': typeof AppMovementsNewRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/catalogo': typeof AppCatalogoIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/movements': typeof AppMovementsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/actividades': typeof AppActividadesRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipos': typeof AppEquiposRoute
  '/reorden': typeof AppReordenRoute
  '/settings': typeof AppSettingsRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/movements/new': typeof AppMovementsNewRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/catalogo': typeof AppCatalogoIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/movements': typeof AppMovementsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/actividades': typeof AppActividadesRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipos': typeof AppEquiposRoute
  '/_app/reorden': typeof AppReordenRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/catalogo/$id': typeof AppCatalogoIdRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/movements/$id': typeof AppMovementsIdRoute
  '/_app/movements/new': typeof AppMovementsNewRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/_app/catalogo/': typeof AppCatalogoIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/movements/': typeof AppMovementsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/actividades'
    | '/chatbot'
    | '/dashboard'
    | '/equipos'
    | '/reorden'
    | '/settings'
    | '/catalogo/$id'
    | '/clients/$id'
    | '/movements/$id'
    | '/movements/new'
    | '/suppliers/$id'
    | '/catalogo'
    | '/clients'
    | '/movements'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/actividades'
    | '/chatbot'
    | '/dashboard'
    | '/equipos'
    | '/reorden'
    | '/settings'
    | '/catalogo/$id'
    | '/clients/$id'
    | '/movements/$id'
    | '/movements/new'
    | '/suppliers/$id'
    | '/catalogo'
    | '/clients'
    | '/movements'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/_app/actividades'
    | '/_app/chatbot'
    | '/_app/dashboard'
    | '/_app/equipos'
    | '/_app/reorden'
    | '/_app/settings'
    | '/_app/catalogo/$id'
    | '/_app/clients/$id'
    | '/_app/movements/$id'
    | '/_app/movements/new'
    | '/_app/suppliers/$id'
    | '/_app/catalogo/'
    | '/_app/clients/'
    | '/_app/movements/'
    | '/_app/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reorden': {
      id: '/_app/reorden'
      path: '/reorden'
      fullPath: '/reorden'
      preLoaderRoute: typeof AppReordenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos': {
      id: '/_app/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof AppEquiposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actividades': {
      id: '/_app/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof AppActividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/': {
      id: '/_app/movements/'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/': {
      id: '/_app/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/new': {
      id: '/_app/movements/new'
      path: '/movements/new'
      fullPath: '/movements/new'
      preLoaderRoute: typeof AppMovementsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/$id': {
      id: '/_app/movements/$id'
      path: '/movements/$id'
      fullPath: '/movements/$id'
      preLoaderRoute: typeof AppMovementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/$id': {
      id: '/_app/catalogo/$id'
      path: '/catalogo/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof AppCatalogoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActividadesRoute: typeof AppActividadesRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquiposRoute: typeof AppEquiposRoute
  AppReordenRoute: typeof AppReordenRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCatalogoIdRoute: typeof AppCatalogoIdRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppMovementsIdRoute: typeof AppMovementsIdRoute
  AppMovementsNewRoute: typeof AppMovementsNewRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppCatalogoIndexRoute: typeof AppCatalogoIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppMovementsIndexRoute: typeof AppMovementsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActividadesRoute: AppActividadesRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquiposRoute: AppEquiposRoute,
  AppReordenRoute: AppReordenRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCatalogoIdRoute: AppCatalogoIdRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppMovementsIdRoute: AppMovementsIdRoute,
  AppMovementsNewRoute: AppMovementsNewRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppCatalogoIndexRoute: AppCatalogoIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppMovementsIndexRoute: AppMovementsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
